config/routes.rb
Rails.application.routes.draw do
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/update'
  get 'requests/destroy'
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "leads#new"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "users/registrations"}
  resources :leads, only: [:index, :new, :create, :show]
  # resources :videos, only: [:index, :new, :create, :destroy]
  resources :blogs
  resources :services
  resources :about, only: :index
  resources :espanol, only: :index
  resources :terms_of_use, only: :index  
  resources :requests, except: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :blogs
  has_and_belongs_to_many :videos
  has_and_belongs_to_many :requests
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :edit, :create, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @lead = Lead.new
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :request_ids => [])
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= render 'layouts/errors', active_object: @service %>

<div class="container">
  <%= bootstrap_form_with(model: service, local: true) do |form| %>

      <%= form.text_field :name %>
      <%= form.cktext_area :description, ckeditor: { language: 'en'} %>
      <%= form.collection_check_boxes :request_ids, Request.all, :id, :name, label: "Request types" %>
      <%= form.submit %>
  <% end %>
</div>

app/views/services/_services_heading.html.erb
<!-- Header -->
<div class="jumbotron jumbobackground" id="services_bg"">
  <div class="text-white text-center py-5 px-4 my-5">
    <div>
      <h1 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Services</strong></h1>
    </div>
  </div>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<%= render 'services_heading' %>
<div class="container">
  <% if user_signed_in? %>
    <%= link_to 'New Service', new_service_path %>
  <% else %>
  <% end %>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Request Type</th>
          <th scope="col" colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% row_counter = 0 %>
        <% @services.each do |service| %>
          <tr>
            <th scope="row"><%= row_counter += 1 %></th>
            <td><%= service.name %></td>
            <td>
              <% service.requests.each do |request| %>
                <%= request.name %> <br>
              <% end %>
            </td>
            <td><%= link_to 'Show', service %></td>
            <% if user_signed_in? %>
              <td><%= link_to 'Edit', edit_service_path(service) %></td>
              <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<%= render 'services_heading' %>
<div class="container">
  <div class="row">
    <!-- Service Content Column -->
    <div class="col-lg-12">
      <!-- Title -->
      <h1 class="mt-4"><%= @service.name %></h1>
      <!-- Service Content -->
      <p class="lead"><%= @service.description.html_safe %></p>
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_service_path(@service) %> |
        <%= link_to 'Back', services_path %>
      <% else %>
      <% end %>
    </div>
  </div>
</div>
<br>

<% if @service.requests.any? %>
<div class="container">
  <hr>
  <div class="row">
    <div class="col-lg-12">
      <h4>Contact us about:</h4>
      <br>
    </div>
  </div>
  <div class="d-flex justify-content-center flex-wrap">
      <!-- Button trigger modal -->
        <% @service.requests.each do |request| %>
        <div class="mr-2 mb-2">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ContactForm">
            <%= request.name %>
          </button>
        </div>
        <% end %>
        <% else %>
        <% end %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="ContactForm" tabindex="-1" role="dialog" aria-labelledby="ContactFormLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="ContactFormLabel">Contact Form</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'layouts/form', lead: @lead %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @service.blogs.any? %>
<div class="container">
  <hr>
  <h4>Here are some posts related to </h4>
  <span class="badge badge-primary" id="service_links"><%= link_to @service.name, service_path(@service) %></span>
  <div class="row">
    <% @service.blogs.each do |blog| %>
    <div class=" col-md-6 col-lg-4 mb-3">
      <div class="card h-100">
        <a href="<%= blog_path(blog) %>">
          <img class="card-img-top" src="<%= blog.picture.url %>" alt="Card image cap">
        </a>
        <div class="card-body">
          <a href="<%= blog_path(blog) %>">
            <h5 class="card-title"><%= blog.title %></h5>
          </a>
          <p class="card-text"><%= strip_tags(blog.content.truncate(250)) %></p>
        </div>
        <div class="card-footer">
          <p class="card-text"><small class="text-muted">Published by <%= mail_to(blog.user.email) %></small></p>
          <p class="card-text"><small class="text-muted">Last updated <%= time_ago_in_words(blog.updated_at) %> ago</small></p>
          <p class="card-text">
            Tags:
            <% blog.services.each do |service| %>
              <span class="badge badge-primary" id="service_links"><%= link_to service.name, service_path(service) %></span>
            <% end %>
            <br>
          </p>

          <p><%= link_to('Show More', blog_path(blog) , class: "btn btn-primary") %></p>
          <% if user_signed_in? %>
              <p><%= link_to 'Edit', edit_blog_path(blog) %></p>
              <p><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% else %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<% end %>