config/routes.rb
Rails.application.routes.draw do
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/update'
  get 'requests/destroy'
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "leads#new"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "users/registrations"}
  resources :leads, only: [:index, :new, :create, :show]
  # resources :videos, only: [:index, :new, :create, :destroy]
  resources :blogs
  resources :services
  resources :about, only: :index
  resources :espanol, only: :index
  resources :terms_of_use, only: :index  
  resources :requests, except: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_and_belongs_to_many :services
  belongs_to :user
  validates :title, :content, presence: true
  mount_uploader :picture, PictureUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    ensure_ownership
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    ensure_ownership
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    #Make sure that a post can be changed only by the creator of the post
    def ensure_ownership
      if user_signed_in? && @blog.user != current_user
        redirect_to blogs_path
        flash[:alert] = "You are not allowed to change this record."
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :picture, :service_ids => [])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= render 'layouts/errors', active_object: @blog %>

<div class="container">
  <%= bootstrap_form_with(model: blog, local: true) do |form| %>

      <%= form.text_field :title %>
      <%= form.cktext_area :content, ckeditor: { language: 'en'} %>
      <%= form.collection_check_boxes :service_ids, Service.all, :id, :name, label: "Services" %>
      <%= form.file_field :picture %>
      <%= form.hidden_field :picture_cache %>
      <%= form.check_box :remove_picture %>
      <%= form.submit %>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<!-- Header -->
<div class="jumbotron jumbobackground" id="blogs_bg"">
  <div class="text-white text-center py-5 px-4 my-5">
    <div>
      <h1 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Blog Posts</strong></h1>
    </div>
  </div>
</div>

<div class="container">
  <% if user_signed_in? %>
    <span><%= link_to 'New Blog Post', new_blog_path %></span>
  <% else %>
  <% end %>
  <div class="row">
    <% @blogs.each do |blog| %>
    <div class=" col-md-6 col-lg-4 mb-3">
      <div class="card h-100">
        <a href="<%= blog_path(blog) %>">
          <img class="card-img-top" src="<%= blog.picture.url %>" alt="Card image cap">
        </a>
        <div class="card-body">
          <a href="<%= blog_path(blog) %>">
            <h5 class="card-title"><%= blog.title %></h5>
          </a>
          <p class="card-text"><%= strip_tags(blog.content.truncate(220)) %></p>
        </div>
          <div class="card-footer">
            <p class="card-text"><small class="text-muted">Published by <%= mail_to(blog.user.email) %></small></p>
            <p><%= link_to('Show More', blog_path(blog) , class: "btn btn-primary") %></p>
            <% if user_signed_in? %>
                <p><%= link_to 'Edit', edit_blog_path(blog) %></p>
                <p><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% else %>
            <% end %>
          </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-10 post-content">
      <!-- Title -->
      <h1 class="mt-4"><%= @blog.title %></h1>
      <!-- Author -->
      <p class="lead">
        by <%= mail_to(@blog.user.email) %>
      </p>
        <hr>
      <!-- Tags -->
      <h3 class="mt-4">Related services</h3>
      <p>
        <% @blog.services.each do |service| %>
          <span class="badge badge-primary" id="service_links"><%= link_to service.name, service_path(service) %></span>
        <% end %>
        <br>
      </p>
        <hr>
      <!-- Preview Image -->
      <img class="img-fluid rounded" src="<%= @blog.picture.url %>" alt="">
        <hr>
      <!-- Post Content -->
      <p class="lead"><%= @blog.content.html_safe %></p>
      <hr>
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_blog_path(@blog) %> |
      <% else %>
      <% end %>
      <%= link_to 'Show all Blog Posts', blogs_path %>
    </div>
  </div>
</div>