config/routes.rb
Rails.application.routes.draw do
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/update'
  get 'requests/destroy'
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "leads#new"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "users/registrations"}
  resources :leads, only: [:index, :new, :create, :show]
  # resources :videos, only: [:index, :new, :create, :destroy]
  resources :blogs
  resources :services
  resources :about, only: :index
  resources :espanol, only: :index
  resources :terms_of_use, only: :index  
  resources :requests, except: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  has_and_belongs_to_many :services
  validates :name, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to requests_url, notice: 'Request type was successfully created.' }
        format.json { redirect_to requests_url, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to requests_url, notice: 'Request type was successfully updated.' }
        format.json { redirect_to requests_url, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= render 'layouts/errors', active_object: @request %>

<div class="container">
  <%= bootstrap_form_with(model: request, local: true) do |form| %>

      <%= form.text_field :name %>
      <%= form.submit %>
  <% end %>
</div>

app/views/requests/_requests_heading.html.erb
<!-- Header -->
<div class="jumbotron jumbobackground" id="services_bg"">
  <div class="text-white text-center py-5 px-4 my-5">
    <div>
      <h1 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Request Types</strong></h1>
    </div>
  </div>
</div>

app/views/requests/edit.html.erb
<h1>Editing Request Type</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<%= render 'requests_heading' %>
<div class="container">
  <% if user_signed_in? %>
    <%= link_to 'New Request Type', new_request_path %>
  <% else %>
  <% end %>
  <div class="table-responsive">
    <table class="table table-striped  table-sm">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col" colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% row_counter = 0 %>
        <% @requests.each do |request| %>
          <tr>
            <th scope="row"><%= row_counter += 1 %></th>
            <td><%= request.name %></td>
            <% if user_signed_in? %>
              <td><%= link_to 'Edit', edit_request_path(request) %></td>
              <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container">
  <h1>New Request Type</h1>

  <%= render 'form', request: @request %>

  <%= link_to 'Back', requests_path %>
</div>