config/routes.rb
Rails.application.routes.draw do
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/create'
  get 'requests/update'
  get 'requests/destroy'
  mount Ckeditor::Engine => '/ckeditor'
  root :to => "leads#new"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "users/registrations"}
  resources :leads, only: [:index, :new, :create, :show]
  # resources :videos, only: [:index, :new, :create, :destroy]
  resources :blogs
  resources :services
  resources :about, only: :index
  resources :espanol, only: :index
  resources :terms_of_use, only: :index  
  resources :requests, except: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
  <% if active_object.errors.any? %>
  <div class="modal" id="errorsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog alert alert-danger" role="document alert">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= pluralize(active_object.errors.count, "error") %> prohibited this record from being saved:</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <ul>
          <% active_object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <script type="text/javascript">
    $(window).on('load',function(){
        $('#errorsModal').modal('show');
    });
</script>

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-light bg-light">
  <p>
    <%= link_to "Terms of Use", terms_of_use_index_path %>
  </p>
<address>

  | T. <a href="tel:+1-647-381-5323">(647) 381-5323</a> | F. (647) 695-6993
  <br>
  | <%= mail_to "antonio@workplacelegal.ca" %>
  <br>
  | <%= link_to "80 Kincort St, 2nd Floor, Toronto, ON M6M 5G1", 'https://www.google.com/maps/place/80+Kincort+St+2nd+Floor,+York,+ON+M6M+5G1/@43.6993539,-79.471962,17z/data=!3m1!4b1!4m5!3m4!1s0x882b33e20e561ae9:0x824d444fc42e4ad9!8m2!3d43.6993539!4d-79.4697733', target: :_blank %>
  <br>
  | <%= link_to "www.workplacelegal.ca" %>
  <br>
  | Follow us:
    <%= link_to(icon('fab', 'twitter-square', class: 'icons'), "https://twitter.com/antophranco", 'aria-label': "Go to my twitter account", target: :_blank, data: { confirm: "You are about to leave this site, do you want to continue?" }) %>
    <%= link_to(icon('fab', 'linkedin', class: 'icons'), "https://www.linkedin.com/in/antonio-f-urdaneta-92299a32/", 'aria-label': "Go to my linkedin account", target: :_blank, data: { confirm: "You are about to leave this site, do you want to continue?" }) %>
</address>

</footer>

app/views/layouts/_form.html.erb
<%= render 'layouts/errors', active_object: @lead %>

<div class="container">
  <%= bootstrap_form_with(model: lead, local: true) do |form| %>

      <%= form.text_field :first_name %>
      <%= form.text_field :last_name %>
      <%= form.select :language, ['English', 'Spanish'], :prompt => 'Choose a language', toggle: true%>
      <%= form.phone_field :phone %>
      <%= form.email_field :email %>
      <%= form.text_area :issue, label: 'How can we help?' %>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary mb-3" data-toggle="collapse" data-target=".clientRelationshipMessage">
        Submit
      </button>
      <br>
      <!-- Modal -->
      <div class="collapse clientRelationshipMessage">
        <div class="card card-body client-message">
          <p>The submission of this form does not establish a lawyer-client relationship</p>
          <%= form.submit "Ok" %>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
    <% flash.each do |key, value| %>
    <div class="container">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= content_tag :div, value, class: "flash #{key}" %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <%= link_to(image_tag("logo.png", :alt => "logo", width:"70", height:"70", :title => "Workplace Legal"), root_path, class: "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to "All Services", services_path, class: "dropdown-item" %>
          <% else %>
          <% end %>

          <% Service.all.order(:name).each do |service| %>
              <%= link_to service.name, service_path(service), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Blog Posts', blogs_path, class: "nav-link" %>
      </li>
      <!-- <li class="nav-item">
        <#%= link_to 'Videos', videos_path, class: "nav-link" %>
      </li> -->
      <li class="nav-item">
        <%= link_to 'Acceso a Justicia', espanol_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_index_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Leads', leads_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Request Types', requests_path, class: "nav-link" %>
      </li>
      <% else %>
      <% end %>
    </ul>
    <ul class="navbar-nav mr-right">
      <li class="navbar-text text-white">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to 'Call us | (647) 381-5323', 'tel:+1-647-381-5323', class: "nav-link" %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-CA">
  <head>
    <title>Workplace Legal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icons/favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" id="messages">
      <%= render '/layouts/messages' %>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
    <%#= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>